apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - canary_bk.yaml
  - deployment_m.yaml
  - hpa.yaml
  - gateway-route.yaml
images:
  - name: ghcr.io/stefanprodan/podinfo
    newName: ghcr.io/stefanprodan/podinfo
    newTag: 5.0.1
